name: 'Build docker image'
on: 
  # Auto build on push to main branch
  push:
    paths-ignore:
      - “README.md”
      - ".gitignore"
      - "LICENSE"
    branches:
      - main
  # Auto build @ every day 6:00am
  schedule:
    - cron: '0 6 * * *'
jobs:
  openwrt-builder:
    name: 'Build docker image'
    runs-on: ubuntu-latest
    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
        run:
          shell: bash
    steps:
    - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
    - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
    - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."

    # Checkout the repository to the GitHub Actions runner
    - name: 'Checkout the repository to the GitHub Actions runner'
      uses: actions/checkout@v2

    # Set up QEMU
    - name: 'Set up QEMU'
      uses: docker/setup-qemu-action@v1

    # Login to DockerHub with username and token
    - name: Login to DockerHub with username and token
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # Build image and push to DockerHub
    - name: "Build image and push to DockerHub"
      uses: docker/build-push-action@v2
      with:
        context: ./openwrt-builder/
        push: true
        tags: sbilly/openwrt-builder:latest

  openwrt-builder-branch:
    name: 'Build openwrt-builder branch images'
    strategy:
      matrix:
        branch: ["lede-17.01", "openwrt-18.06", "openwrt-19.07", "openwrt-21.02", "master"]
    runs-on: ubuntu-latest
    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
        run:
          shell: bash
    steps:
    - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
    - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
    - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."

    # Checkout the repository to the GitHub Actions runner
    - name: 'Checkout the repository to the GitHub Actions runner'
      uses: actions/checkout@v2

    # Set up QEMU
    - name: 'Set up QEMU'
      uses: docker/setup-qemu-action@v1

    # Login to DockerHub with username and token
    - name: Login to DockerHub with username and token
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # Build image and push to DockerHub
    # - name: "Build image and push to DockerHub"
    #   uses: docker/build-push-action@v2
    #   with:
    #     context: ./openwrt-builder-branch/
    #     push: true
    #     tags: sbilly/openwrt-builder:${{ matrix.branch }}


    Build image and push to DockerHub
    - name: "Build image and push to DockerHub"
      run: docker build -t sbilly/openwrt-builder:${{ matrix.branch }} --build-arg OPENWRT_BRANCH=${{ matrix.branch }} ./openwrt-builder-branch/
